schema: ./src/lib/graphql/schema.ts
require:
  - ts-node/register
documents: 
  - src/**/*.graphql
  - src/**/*.tsx
overwrite: true
extensions:
  codegen:
    generates:
      generated/schema.graphql:
        plugins:
          - schema-ast
      generated/gql:
        preset: gql-tag-operations-preset
