---
schema: ./src/common/graphql/schema.ts
require:
  - ts-node/register
documents: 'src/**/!(*.generated).{ts,tsx}'
overwrite: true
extensions:
  codegen:
    generates:
      generated/schema.graphql:
        plugins:
          - schema-ast
      src/@types/graphql.d.ts:
        - typescript
      src/:
        preset: near-operation-file
        presetConfig:
          extension: .ts
          baseTypesPath: '@types/graphql.d.ts'
          folder: _gql_
        plugins:
          - typed-document-node
          - typescript-operations
