# Default configuration for Luzzle Web Explorer.
# These values can be overridden by a user-provided config.yaml
# or by environment variables.

# Defines the key URLs required for the application to function correctly.
url:
  # The primary, public-facing URL of this Luzzle Explorer instance.
  app: ''

  # The base URL for _app assets hosted on a separate CDN or file server.
  app_assets: ''

  # The base URL for assets hosted on a separate CDN or file server.
  luzzle_assets: ''

  # The URL for the Luzzle Editor instance, used for edit links.
  editor: 'http://editor.localhost'

# general app text strings
text:
  title: 'Luzzle Explorer'
  description: 'A Luzzle Explorer instance'

paths:
  # The connection URL for the database.
  database: './data/luzzle.sqlite'

theme:
  globals:
    shadows-raised: '0px 3px 1px -2px rgba(251 241 199 / 20%), 0px 2px 2px 0px rgba(251 241 199 / 14%), 0px 1px 5px 0px rgba(0 0 0 / 12%)'
    fonts-mono: 'monaco, monospace'
    font-sizes-xxs: '0.7rem'
    font-sizes-xs: '0.825rem'
    font-sizes-small: '1rem'
    font-sizes-normal: '1.25rem'
    font-sizes-medium: '1.5rem'
    font-sizes-large: '1.825rem'
    font-sizes-xl: '2rem'
    font-sizes-xxl: '3rem'
    font-sizes-mobile-responsive-factor: '4/5'
    font-sizes-root: '22px'
    font-weights-light: '300'
    font-weights-normal: '400'
    font-weights-medium: '500'
    font-weights-semibold: '550'
    fonteights-bold: '650'
    radii-none: '0'
    radii-small: '0.25rem'
    radii-medium: '0.375rem'
    radii-large: '0.5rem'
    radii-xl: '0.75rem'
    radii-x2l: '1rem'
    radii-x3l: '1.5rem'
    radii-x4l: '2.5rem'
    radii-full: '9999px'
    breakpoints-phone: '640'
    breakpoints-tablet: '768'
    breakpoints-laptop: '1024'
    breakpoints-desktop: '1280'
    space-1: '0.25rem'
    space-2: '0.5rem'
    space-3: '0.75rem'
    space-4: '1rem'
    space-5: '1.25rem'
    space-6: '1.5rem'
    space-7: '1.75rem'
    space-8: '2rem'
    space-9: '2.25rem'
    space-10: '2.5rem'
    space-0-5: '0.125rem'
    space-1-5: '0.375rem'
    space-2-5: '0.625rem'
    space-3-5: '0.875rem'
  dark:
    colors-primary: '#3b82f6'
    colors-on-primary: '#ffffff'
    colors-primary-container: '#0d6efd'
    colors-on-primary-container: '#cfe2ff'
    colors-secondary: '#adb5bd'
    colors-on-secondary: '#212529'
    colors-secondary-container: '#495057'
    colors-on-secondary-container: '#d3d3d4'
    colors-tertiary: '#adb5bd'
    colors-on-tertiary: '#212529'
    colors-tertiary-container: '#495057'
    colors-on-tertiary-container: '#d3d3d4'
    colors-error: '#f87171'
    colors-on-error: '#4f0b0b'
    colors-error-container: '#dc3545'
    colors-on-error-container: '#f8d7da'
    colors-surface: '#121212'
    colors-surface-dim: '#1f1f1f'
    colors-surface-bright: '#333333'
    colors-surface-inverse: '#e9ecef'
    colors-on-surface: '#e9ecef'
    colors-on-surface-variant: '#adb5bd'
    colors-on-surface-inverse: '#121212'
    colors-surface-container-lowest: '#1f1f1f'
    colors-surface-container-low: '#333333'
    colors-surface-container: '#4f4f4f'
    colors-surface-container-high: '#666666'
    colors-surface-container-highest: '#7f7f7f'
    colors-shadow: 'hsla(0, 0%, 0%, 0.5)'
    colors-outline: '#6c757d'
    colors-outline-variant: '#495057'
  light:
    colors-primary: '#0d6efd'
    colors-on-primary: '#ffffff'
    colors-primary-container: '#cfe2ff'
    colors-on-primary-container: '#084298'
    colors-secondary: '#6c757d'
    colors-on-secondary: '#ffffff'
    colors-secondary-container: '#d3d3d4'
    colors-on-secondary-container: '#41464b'
    colors-tertiary: '#6c757d'
    colors-on-tertiary: '#ffffff'
    colors-tertiary-container: '#d3d3d4'
    colors-on-tertiary-container: '#41464b'
    colors-error: '#dc3545'
    colors-on-error: '#ffffff'
    colors-error-container: '#f8d7da'
    colors-on-error-container: '#842029'
    colors-surface: '#f8f9fa'
    colors-surface-dim: '#e9ecef'
    colors-surface-bright: '#ffffff'
    colors-surface-inverse: '#212529'
    colors-on-surface: '#212529'
    colors-on-surface-variant: '#495057'
    colors-on-surface-inverse: '#f8f9fa'
    colors-surface-container-lowest: '#ffffff'
    colors-surface-container-low: '#e9ecef'
    colors-surface-container: '#dee2e6'
    colors-surface-container-high: '#ced4da'
    colors-surface-container-highest: '#adb5bd'
    colors-shadow: 'hsla(0, 0%, 0%, 0.15)'
    colors-outline: '#6c757d'
    colors-outline-variant: '#ced4da'
